### ISSUE TITLE
Great project - submit back into core OpenWhisk?

### ISSUE THREAD

**Issue by jthomas** [cliffjansen/amqp-wsk-feed#2]
This looks like a great additional trigger feed for the platform. It fills a gap in the event sources to have a message queue. Do you think you will be submitting this as a proposal for inclusion in the core platform?

**Comment by cliffjansen** [comment]
@jthomas yes I would be very happy to do so.  The design has tried to closely match characteristics of existing core packages. Let me know if there is anything I can do to help make this happen.  FYI I am currently a committer on the Apache Qpid project and very active in AMQP 1.0.

**Comment by jthomas** [comment]
It looks great. I'll have a look over and raise issues for anything I find.

If you're familiar with Apache it should be simple to submit this back. 

Can you send a message to the openwhisk dev mailing list proposing the contribution? 
https://openwhisk.apache.org/contact

Feed providers will be in a separate repo. The committers can discuss the proposal and (hopefully) work out how to get this added.
